[package]
name = "lpirs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.4", features = ["derive"] }
diffs = "0.4.1"
nix = "0.26.2"
rand = "0.8.5"
